# Generated by Django 5.0.6 on 2024-07-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0004_firearm_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearm',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
