# Generated by Django 5.0.6 on 2024-06-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_clientapplication_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='region',
            field=models.CharField(default='Nairobi', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Pending_Interview', 'Pending_Interview'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
