# Generated by Django 5.0.6 on 2024-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_clientapplication_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplication',
            name='good_conduct',
            field=models.FileField(blank=True, null=True, upload_to='client/good_conduct'),
        ),
    ]
