# Generated by Django 5.0.6 on 2024-07-08 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_clientapplication_good_conduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapplication',
            name='address',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ClientLicence',
            fields=[
                ('clientappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientapp.clientappmodel')),
                ('license_number', models.CharField(max_length=100)),
                ('issued_on', models.DateField()),
                ('expiry_on', models.DateField()),
                ('renewed_on', models.DateField(blank=True, null=True)),
                ('revoked_on', models.DateField(blank=True, null=True)),
                ('interview_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Awaiting Payment Approval', 'Awaiting Payment Approval'), ('Awaiting Interview', 'Awaiting Interview'), ('Expired', 'Expired'), ('Revoked', 'Revoked')], default='Active', max_length=60)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_licence_application', to='clientapp.clientapplication')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Client_licence', to='clientapp.clientprofile')),
            ],
            bases=('clientapp.clientappmodel',),
        ),
        migrations.AddField(
            model_name='clientfirearm',
            name='licence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_firearm_licence', to='clientapp.clientlicence'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LicencePayment',
            fields=[
                ('clientappmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientapp.clientappmodel')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_on', models.DateField(blank=True, null=True)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_payment', to='clientapp.clientlicence')),
            ],
            bases=('clientapp.clientappmodel',),
        ),
    ]
